// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGCIqk4jwVZh4eO6TuhndxQS7WfbSBHr4',
    appId: '1:906517241771:web:4584ee3c71ccfc1f3afcee',
    messagingSenderId: '906517241771',
    projectId: 'safemate-3dada',
    authDomain: 'safemate-3dada.firebaseapp.com',
    storageBucket: 'safemate-3dada.firebasestorage.app',
    measurementId: 'G-0CRX5VW2V8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyawZDok9OIhWUPxPdQhJGYB44SpbWC2o',
    appId: '1:906517241771:android:084840bed8bd2be33afcee',
    messagingSenderId: '906517241771',
    projectId: 'safemate-3dada',
    storageBucket: 'safemate-3dada.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAog7iZceNL5ZblRlv8GPfujxhnku5UIOU',
    appId: '1:906517241771:ios:846f26f5b1a6cf8b3afcee',
    messagingSenderId: '906517241771',
    projectId: 'safemate-3dada',
    storageBucket: 'safemate-3dada.firebasestorage.app',
    iosBundleId: 'com.example.safeMate',
  );
}
